### ISSUE TITLE
slkearn and skl2onnx dependencies

### ISSUE THREAD

**Issue by adrinjalali** [sdpython/mlprodict#37]
Shouldn't sklearn and skl2onnx also be in `install_requires`?

**Comment by sdpython** [comment]
I'm puzzled with that because this package implements converters (sklearn is needed) and a runtime (sklearn is not needed). Maybe a better error message would sufficient?

**Comment by adrinjalali** [comment]
Maybe, but the issue is that by default it installs none of them, and that means none of those two functionalities of the package work.

**Comment by sdpython** [comment]
I defined options. ``pip install mlprodict[onnx_val]`` should download the necessary packages.
