### ISSUE TITLE
Build for Mac ARM

### ISSUE THREAD

**Issue by hopper-signifyd** [sdpython/mlprodict#487]
It looks like there are wheels built for most major platforms, but arm Macs are noticeably absent. Building from source doesn't work for me. From what I understand, the `setup_requires` part of `setup.py` is problematic.

Can we get a new release cut with a wheel built for arm Macs?

**Comment by xadupre** [comment]
What feature do you need in mlprodict? The main feature was the python runtime for onnx and it is now part of the package onnx more robust than the version implemented here.

**Comment by hopper-signifyd** [comment]
I don't recall my exact use case at the moment since it's been several weeks now. Are you suggesting that we should avoid using `mlprodict`?

**Comment by hopper-signifyd** [comment]
Marking this as closed for now since (1) building for Mac ARM is 10x the cost of building for other platforms (or something silly like that and (2) I'm not using `mlprodict` anymore
